// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElL: typeof import('element-plus/es')['ElL']
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
